#!/bin/bash

# Descritpion: This cp script used to enhance the cp tool
# Author: Yangyi_Peng
# Date: 2016/12/13

function help()
{
    echo "Usage: yy_cp source_file/source_dir dst_file/dst_dir"
    echo "1: Copy file to file"
    echo "Example: yy_cp source ~/test"
    echo "2: Copy file/dir to direcory which not exist yet:"
    echo "Example: yy_cp source -d ~/temp/"
}


if [ $# -eq 2 ]; then
    src=$1
    dst=$2
    if [ -f "$dst" ]; then
	echo "The $dst already exist, do you want to replace it?"
	read -p "Please input Y/y to confirm or any other key to cancel: " input
        if [ -z "$input" ]; then
            exit
        elif [ "$input" = "Y" -o "$input" = "y" ]; then
            echo "Replace $dst..."
            cp $src $dst
            echo "Done!"
        else
            exit
        fi 
    else
        path=$(echo $dst | sed "s/\(.*\/.*\/\).*/\1/")
        if [ -d "$path" ]; then
	    cp $src $dst -r
        else
	    mkdir -p $path
            cp $src $dst -r
        fi
    fi
elif [ $# -eq 3 ]; then
    src=$1
    dst=$3
    arg=$2
    if [ "$arg" = "-d" ]; then
	if [ -f "$dst" ]; then
	    echo "The $dst is a existed normal file, please confirm it."
	    read -p "Please input Y/y to confirm or any other key to cancel: " input
            if [ -z "$input" ]; then
                exit
            elif [ "$input" = "Y" -o "$input" = "y" ]; then
                echo "Replace $dst..."
                cp $src $dst
                echo "Done!"
            else
                exit
            fi
        elif [ ! -d "$dst" ]; then
            mkdir -p $dst
            cp $src $dst -r
	else
            cp $src $dst -r
        fi
    else
	help
    fi
else
    help
fi
